name: cdk
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.11.12=h4c7d964_0
  - configargparse=1.7.1=pyhe01879c_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - liblzma=5.8.1=h2466b09_0
  - libsqlite=3.49.1=h67fdade_2
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.11.11=h3f84c4b_2_cpython
  - setuptools=78.1.0=pyhff2d567_0
  - tk=8.6.13=h5226925_1
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - dask==2025.3.0
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - geopandas==1.1.1
      - grpcio==1.76.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - locket==1.0.0
      - markdown==3.10
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - partd==1.4.2
      - pillow==11.1.0
      - protobuf==6.33.0
      - pyarrow==19.0.1
      - pykrige==1.7.2
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyproj==3.7.2
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.21
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-gstat==1.0.19
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - shapely==2.1.1
      - six==1.17.0
      - slicer==0.0.8
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - toolz==1.0.0
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tqdm==4.67.1
      - typing-extensions==4.13.1
      - tzdata==2025.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - zipp==3.21.0
prefix: C:\Users\12818\.conda\envs\gan

